@echo off
echo 🔧 Fixing Java Home Configuration for Gradle...
echo ==================================================

echo Step 1: Checking current Java installations...
java -version 2>nul
if %errorlevel% neq 0 (
    echo ❌ Java not found in PATH
) else (
    echo ✅ Java found in PATH
)

echo.
echo Step 2: Setting up JAVA_HOME environment variable...

REM Find Java installations
set "JAVA_FOUND="
for /f "tokens=*" %%i in ('dir /b /s "C:\Program Files\Java\jdk*" 2^>nul') do (
    if exist "%%i\bin\java.exe" (
        set "JAVA_HOME=%%i"
        set "JAVA_FOUND=1"
        echo Found JDK: %%i
        goto :found_java
    )
)

for /f "tokens=*" %%i in ('dir /b /s "C:\Program Files (x86)\Java\jdk*" 2^>nul') do (
    if exist "%%i\bin\java.exe" (
        set "JAVA_HOME=%%i"
        set "JAVA_FOUND=1"
        echo Found JDK: %%i
        goto :found_java
    )
)

:found_java
if "%JAVA_FOUND%"=="" (
    echo ❌ No JDK found in standard locations
    echo Please install JDK 17 or later
    pause
    exit /b 1
)

echo.
echo Step 3: Setting JAVA_HOME to: %JAVA_HOME%
setx JAVA_HOME "%JAVA_HOME%"
setx PATH "%PATH%;%JAVA_HOME%\bin"

echo.
echo Step 4: Creating gradle.properties with Java home configuration...
if not exist "%USERPROFILE%\.gradle" mkdir "%USERPROFILE%\.gradle"

echo # Gradle Java Home Configuration > "%USERPROFILE%\.gradle\gradle.properties"
echo # Generated by fix-java-home.bat >> "%USERPROFILE%\.gradle\gradle.properties"
echo org.gradle.java.home=%JAVA_HOME% >> "%USERPROFILE%\.gradle\gradle.properties"
echo org.gradle.jvmargs=-Xmx4096m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 >> "%USERPROFILE%\.gradle\gradle.properties"
echo org.gradle.daemon=true >> "%USERPROFILE%\.gradle\gradle.properties"
echo org.gradle.parallel=true >> "%USERPROFILE%\.gradle\gradle.properties"
echo org.gradle.configureondemand=true >> "%USERPROFILE%\.gradle\gradle.properties"

echo.
echo Step 5: Creating project-level gradle.properties...
echo # Project Gradle Configuration > gradle.properties
echo # Generated by fix-java-home.bat >> gradle.properties
echo org.gradle.java.home=%JAVA_HOME% >> gradle.properties
echo org.gradle.jvmargs=-Xmx4096m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 >> gradle.properties
echo org.gradle.daemon=true >> gradle.properties
echo org.gradle.parallel=true >> gradle.properties
echo org.gradle.configureondemand=true >> gradle.properties

echo.
echo Step 6: Testing Java configuration...
echo Current JAVA_HOME: %JAVA_HOME%
echo.
echo Testing Java version:
"%JAVA_HOME%\bin\java" -version

echo.
echo Step 7: Testing Gradle configuration...
call gradlew --version

echo.
echo ✅ Java Home Configuration Fix Completed!
echo ==================================================
echo Next steps:
echo 1. Restart Android Studio
echo 2. Open your project
echo 3. Let Gradle sync with the new Java configuration
echo 4. Test your chess game
echo ==================================================
pause 